### ISSUE TITLE
Dict contents displayed out of order

### ISSUE THREAD

**Issue by peedrr** [gruns/icecream#103]
As of Python 3.7, standard dictionaries respect and maintain the order that the keys were inserted. When displaying with icecream, the order is not maintained. Easy fix?

**Comment by gruns** [comment]
dicts are pretty printed with python's default pretty printer `pprint`

  * https://docs.python.org/3/library/pprint.html

how large of a problem is the dict order not being preserved for you?

**Comment by alexmojaki** [comment]
pprint has a sort_dicts argument, so `ic.configureOutput(argToStringFunction=lambda x: pprint.pformat(x, sort_dicts=False))` (untested) or something like that should work already

**Comment by gruns** [comment]
@peedrr which would be your desired output? sorted, eg with `sort_dicts`, or order maintained?

any further context or input of yours would is extremely helpful here

**Comment by alexmojaki** [comment]
Maybe I wasn't clear. pprint has sort_dicts=True by default which kills the original order. @peedrr seems to want the order maintained, so sort_dicts=False should do that. I think that's why the argument was created.

**Comment by gruns** [comment]
you were perfectly clear 🙂

from @peedrr's first message, i dont think it was apparent that the dicts were being sorted. i still read 

> As of Python 3.7, standard dictionaries respect and maintain the order that the keys were inserted. When displaying with icecream, the order is not maintained. Easy fix?

as he was more surprised the original order wasn't preserved

but what's still unclear to me is whether there's actually a *problem* with the order not being preserved or if this was just surprising behavior but no problem

**Comment by peedrr** [comment]
Hi guys, thank you for looking into this. I suspected that pretty printing may have something to do with this, I've seen the same behaviour when using pprint.

To answer your queries first:

- Yes, I am hoping to maintain the order of insertion to the original dictionary (which is now the default behaviour in Python > 3.7).
- I wasn't aware that ic/pprint was actually _sorting_ the dicts, this is very interesting and I guess potentially helpful for other users.
- And I certainly wasn't aware that pprint has a kwarg to turn this behaviour off! This is great.

So yes, something similar to pprint's own sort_dicts=False would be the ideal. My preference would be to maintain original order by default, as Python now does, but obviously that decision is in your hands.

Thanks again

**Comment by gruns** [comment]
@peedrr thank you for expounding! 🙌 

the `sort_dicts` param was added in py38

  * https://docs.python.org/3/library/pprint.html#pprint.pformat

what version of python are you running? 3.8+? 

if youre using py38+, the can achieve your desired 

```python
import pprint

from icecream import ic

ic.configureOutput(
    argToStringFunction=lambda o: pprint.pformat(o, sort_dicts=False))
```

if youre running 3.8+, does this suffice for your needs for now?

**Comment by bryan-with-a-y** [comment]
Just wanted to say this would have been a deal breaker for using ic so thank you for the alternative solution! Works perfectly so far

**Comment by gruns** [comment]
@bryan-with-a-y interesting!

im curious: why/how are sorted dicts a deal breaker for you with icecream?

if they're a deal breaker for more folks, like you, we should integrate a better mechanism into the library to disable dict sorting

**Comment by bryan-with-a-y** [comment]
In hindsight I was perhaps a bit overdramatic with it being a deal-breaker, however, when I was new to programming it baffled me that dicts didn't sort keys in insertion order by default. Eventually this did become the default in Python, but it always seemed like it should have been that from the start because when you impose order on things, you can do things with that order that you cannot without it.

That aside, I use dictionaries a lot in my hobbyist programming and it is simply just so much easier to debug dictionaries when you see the keys and values in the order that they were created. If there's no downside to having them sorted in insertion order by default I think it would be a nice change.

**Comment by gruns** [comment]
thank you for expounding!

> If there's no downside to having them sorted in insertion order by default I think it would be a nice change.

right. though some users want the opposite

imagine you print a dict with icecream and then want to look up a specific key, or specific keys, by name. in this case, sorting makes this task easier

you're the first one to want to print dicts in insertion order. as such, im going to leave icecream's implementation as-is and if you, future reader of this issue, want icecream to sort dicts by insertion order instead of sorted order, please re-open this issue and let us know
