### ISSUE TITLE
contextAbsPath can't be set in ic.configureOutput

### ISSUE THREAD

**Issue by MelchiorIm3Tal** [gruns/icecream#128]
coding:
ic.configureOutput(contextAbsPath=True)

leads to: 
Traceback (most recent call last): File "", line 1, in TypeError: IceCreamDebugger.configureOutput() got an unexpected keyword argument 'contextAbsPath'

This is not congruent to the documentation: 
"Configuration

ic.configureOutput(prefix, outputFunction, argToStringFunction, includeContext, contextAbsPath) controls ic()'s output."

**Comment by gruns** [comment]
you likely need to update icecream

```
>>> from icecream import ic
>>> ic.configureOutput(contextAbsPath=True)
>>> import icecream
>>> icecream.__version__
'2.1.2'
```

**Comment by HelinXu** [comment]
Hi @MelchiorIm3Tal , The `contextAbsPath` was only recently added to the source code (2.1.3) and has not been released to PyPI. You may have to install `icecream-2.1.3` from the source code to enable this feature for now.

Also, since it seems people are trying out this new feature, I wonder if it's possible to release `icecream-2.1.3` to PyPI soon :) @gruns

**Comment by gruns** [comment]
icecream v2.1.3 now in pypi. upgrade with

```
pip3 install icecream --upgrade
```

and `contextAbsPath` glory awaits!

another huge thank you to @HelinXu for adding support here! 🙌
