### ISSUE TITLE
IPython magic %time break ic

### ISSUE THREAD

**Issue by off99555** [gruns/icecream#38]
`from snoop import pp` kind of works
but `from icecream import ic` does not work in this context.
![image](https://user-images.githubusercontent.com/15215732/66273816-a65cf780-e8a1-11e9-9251-7e42899ec3b8.png)

If you can't see above image, here's the cell in Jupyter Notebook:
```py
%time pp(2+2)
%time ic(3+3)
```
And here's the output:
```txt
01:26:16.74 LOG:
01:26:16.74 .... <argument> = 4
ic| Error: Failed to access the underlying source code for analysis. Was ic() invoked in an interpreter (e.g. python -i), a frozen application (e.g. packaged with PyInstaller), or did the underlying source code change during execution?
Wall time: 0 ns
Wall time: 34.9 ms
```

**Comment by alexmojaki** [comment]
The source code is genuinely not available. If you try `%time 1/0` you won't see `1/0` in the traceback because it's not saved anywhere. This would require a change on the IPython side, and there's no good reason for them to make that effort. Plus if you're timing something it would be a bad idea to put `ic`, `pp`, or even `print` in there.
